// src/components/ContactForm.vue
<script setup lang="ts">
import { useForm } from '@tanstack/vue-form'
import { toast } from 'vue-sonner'
import { z } from 'zod'
import { Field, FieldDescription, FieldError, FieldGroup } from './ui/field'
import Input from './ui/input/Input.vue'
import FieldLabel from './ui/field/FieldLabel.vue'
import { InputGroup, InputGroupAddon, InputGroupText, InputGroupTextarea } from './ui/input-group'
import Button from './ui/button/Button.vue'
import { h } from 'vue'

const formSchema = z.object({
  contactName: z.string()
    .min(1, 'Name must be at least 1 character.')
    .max(50, 'Name must be at most 50 characters.'),
  contactEmail: z.email(),
  contactDescription: z.string()
    .min(50, 'Description must be at least 50 characters.')
    .max(1000, 'Description must be at most 1000 characters.')
})

const form = useForm({
  defaultValues: {
     contactName: '',
     contactEmail: '',
     contactDescription: '',
  },
  validators: {
    onSubmit: formSchema
  },
  onSubmit: async ({ value }) => {
    console.log(value)
    // toast('You submitted the following values:', {
    //   description: h(
    //     'pre',
    //     {
    //       class: 'bg-code text-code-foreground mt-2 w-[320px] overflow-x-auto rounded-md p-4',
    //     },
    //     h('code', JSON.stringify(value, null, 2)),
    //   ),
    //   position: 'bottom-right',
    //   class: 'flex flex-col gap-2',
    //   style: {
    //     '--border-radius': 'calc(var(--radius)  + 4px)',
    //   },
    // })
    toast.success("Contact details sent!", {
      description: "I'll get back to you as soon as possible, thank you!"
    })
  }
})

const isInvalid = (field: any) => {
  return field.state.meta.isTouched && !field.state.meta.isValid
}
</script>

<template>
  <div class="w-full space-y-6">
    <form
      id="contact-form"
      @submit.prevent="form.handleSubmit"
      class="w-full"
    >
      <FieldGroup>
        <form.Field name="contactName">
          <template #default="{ field }">
            <Field :data-invalid="isInvalid(field)">
              <FieldLabel :for="field.name">
                Name
              </FieldLabel>
              <Input
                :id="field.name"
                :name="field.name"
                :model-value="field.state.value"
                :aria-invalid="isInvalid(field)"
                autocomplete="off"
                @blur="field.handleBlur"
                @input="field.handleChange($event.target.value)"
              />
              <FieldError
                v-if="isInvalid(field)"
                :errors="field.state.meta.errors"
              />
            </Field>
          </template>
        </form.Field>

        <form.Field name="contactEmail">
          <template #default="{ field }">
            <Field :data-invalid="isInvalid(field)">
              <FieldLabel :for="field.name">
                Email
              </FieldLabel>
              <Input
                :id="field.name"
                :name="field.name"
                :model-value="field.state.value"
                :aria-invalid="isInvalid(field)"
                type="email"
                @blur="field.handleBlur"
                @input="field.handleChange($event.target.value)"
              />
              <FieldError
                v-if="isInvalid(field)"
                :errors="field.state.meta.errors"
              />
            </Field>
          </template>
        </form.Field>

        <form.Field name="contactDescription">
          <template #default="{ field }">
            <Field :for="field.name">
              <FieldLabel>
                Description
              </FieldLabel>
              <InputGroup>
                <InputGroupTextarea
                  :id="field.name"
                  :name="field.name"
                  :model-value="field.state.value"
                  :rows="5"
                  :aria-invalid="isInvalid(field)"
                  placeholder="What's your project about?"
                  @blur="field.handleBlur"
                  @input="field.handleChange($event.target.value)"
                  class="min-h-24 resize-none"
                />
                <InputGroupAddon align="block-end">
                  <InputGroupText class="tabular-nums">
                    {{ field.state.value?.length ?? 0 }}/1000 characters
                  </InputGroupText>
                </InputGroupAddon>
              </InputGroup>
              <FieldError
                v-if="isInvalid(field)"
                :errors="field.state.meta.errors"
              />
            </Field>
          </template>
        </form.Field>
      </FieldGroup>
    </form>
    <div class="text-center md:col-span-2">
      <Button type="submit" form="contact-form" class="w-full">Submit</Button>
    </div>
  </div>
</template>

// src/components/ContactForm.tsx
import { zodResolver } from "@hookform/resolvers/zod"
import { z } from "zod"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "./ui/form";
import { useForm } from "react-hook-form";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { toast } from "sonner";

const formSchema = z.object({
  contactName: z.string().min(1).max(50),
  contactEmail: z.string().email(),
  contactDescription: z.string().min(1).max(1024)
})

export function ContactForm() {
  return <BaseContactForm />
}

function BaseContactForm() {
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      contactName: "",
      contactEmail: "",
      contactDescription: ""
    }
  })

  function onSubmit(values: z.infer<typeof formSchema>) {
    if (import.meta.env.PROD) {
      const endpoint = `${import.meta.env.PUBLIC_API_URL}/contact`
      console.log(endpoint)

      fetch(endpoint, {
        method: "POST",
        body: JSON.stringify(values),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      })
      .then(() => toast.success("Contact details sent!", {
        description: "I'll get back to you as soon as possible, thank you!"
      }))
      .catch((e) => {
        console.error("Errors", e)
        toast.error("Sorry, something didn't work!", {
          description: "Try again or email me at discovery@sidetrails.dev"
        })
      })
    } else {
      toast.success("Contact details sent!", {
        description: "I'll get back to you as soon as possible, thank you!"
      })
    }
    console.log(values)
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="sm:grid sm:grid-cols-2 sm:gap-x-4 space-y-6 w-full">
        <FormField
          control={form.control}
          name="contactName"
          render={({ field }) => (
            <FormItem>
              <FormLabel className="pb-2">Name</FormLabel>
              <FormControl>
                <Input {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="contactEmail"
          render={({ field }) => (
            <FormItem>
              <FormLabel className="pb-2">Email</FormLabel>
              <FormControl>
                <Input {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="contactDescription"
          render={({ field }) => (
            <FormItem className="w-full sm:col-span-2">
              <FormLabel className="pb-2">Description</FormLabel>
              <FormControl>
                <Textarea rows={5} {...field} />
              </FormControl>
              <FormDescription>What's your project about?</FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <div className="text-center md:col-span-2">
          <Button type="submit" className="w-full">Submit</Button>
        </div>
      </form>
    </Form>
  )
}
