// src/components/navs/MobileNav.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { NavItem } from '.';
import { cn } from "@/lib/utils"
import { MenuIcon } from '@/components/icons';
import {
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { Button } from '@/components/ui/button';


const props = defineProps<{
  items: NavItem[]
  class?: string
}>()

const open = ref(false)
</script>

<template>
  <div :class="cn(
    'bg-background/90 backdrop-blur border rounded-lg shadow-sm',
    props.class
  )">
    <Popover v-model:open="open" :modal="true">
      <PopoverAnchor class="flex justify-between items-center w-full">
        <a href="/" class="flex items-center ml-2">
          <img class="h-8" src="/logo.svg" alt="Side Trails Software Development logo." />
          <p class="font-bold font-heading mt-0.5">
            Side Trails
          </p>
        </a>
        <PopoverTrigger as-child>
          <Button variant="ghost">
            <MenuIcon :open="open" />
            <span class="sr-only">Menu Toggle</span>
          </Button>
        </PopoverTrigger>
      </PopoverAnchor>
      <PopoverContent
        align="start"
        side="bottom"
        :side-offset="8"
        class="bg-background/90 backdrop-blur w-(--reka-popper-anchor-width)"
      >
        <ul class="space-y-3">
          <li v-for="item in props.items" :key="item.label">
            <a :href="item.href">{{ item.label }}</a>
          </li>
          <hr class="border-dashed" />
          <li>
            <a href="https://www.linkedin.com/in/spencerhaan/" target="_blank">LinkedIn</a>
          </li>
          <li>
            <a href="https://github.com/SpencerHaan/side-trails-dev" target="_blank">GitHub</a>
          </li>
        </ul>
      </PopoverContent>
    </Popover>
  </div>
</template>

// src/components/ui/mobile-nav.tsx
import { useState } from "react"
import { Popover, PopoverAnchor, PopoverContent, PopoverTrigger } from "./popover"
import { Button } from "./button"
import { cn } from "@/lib/utils"

export default function MobileNav({
  items,
  className = ""
} : {
  items: { label: string, href: string }[],
  className?: string
}) {
  const [open, setOpen] = useState(false)

  return (
    <div className={cn(
      "bg-background/90 backdrop-blur border rounded-lg shadow-sm",
      className
    )}>
      <Popover open={open} onOpenChange={setOpen} modal={true}>
        <PopoverAnchor className="flex justify-between items-center w-full">
          <a href="/" className="flex items-center ml-2">
            <img className="h-8" src="/logo.svg" alt="Side Trails Software Development logo." />
            <p className="font-bold font-heading mt-0.5">
              Side Trails
            </p>
          </a>
          <PopoverTrigger asChild>
            <Button variant="ghost">
              <MenuIcon open={open} />
              <span className="sr-only">Menu Toggle</span>
            </Button>
          </PopoverTrigger>
        </PopoverAnchor>
        <PopoverContent
          align="start"
          side="bottom"
          sideOffset={8}
          className="bg-background/90 backdrop-blur w-(--radix-popper-anchor-width)"
        >
          <ul className="space-y-3">
            {items.map((item, i) => (
              <MenuLinkItem key={i} {...item} />
            ))}
            <hr className="border-dashed" />
            <MenuLinkItem label="LinkedIn" href="https://www.linkedin.com/in/spencerhaan/" target="_blank" onClick={() => setOpen(false)} />
            <MenuLinkItem label="GitHub" href="https://github.com/SpencerHaan/side-trails-dev" target="_blank" onClick={() => setOpen(false)} />
          </ul>
        </PopoverContent>
      </Popover>
    </div>
  )
}

function MenuIcon({
  open = false
} : {
  open: boolean
}) {
  return (
    <div className="relative w-4 h-4 my-auto">
      <MenuIconLine className={cn(
        "top-1/6",
        open ? "top-1/2 -translate-y-1/2 -rotate-45" : null
      )} />
      <MenuIconLine className={open ? "w-0" : ""} />
      <MenuIconLine className={cn(
        "top-5/6",
        open ? "top-1/2 -translate-y-1/2 rotate-45" : null
      )} />
    </div>
  )
}

function MenuIconLine({
  className = ""
} : {
  className?: string
}) {
  return (
    <div className={cn(
      "absolute bg-foreground rounded w-full h-0.5 top-1/2 left-1/2 -translate-1/2 transition-all duration-300",
      className
    )} />
  )
}

function MenuLinkItem({
  label,
  href,
  target,
  onClick
} : {
  label: string
  href: string
  target?: string
  onClick?: () => void
}) {
  return (
    <li>
      <a href={href} onClick={onClick} target={target}>{label}</a>
    </li>
  )
}
